content_types:
  FileUpload:
    attributes:
      name: string
      file: file
      description: text
  PageArea:
    attributes:
      name: string
      description: string
      content: html
  Chapter:
    attributes:
      title: string
