development:
  secret_key_base: fd816d5a3

test:
  secret_key_base: fd816d5a3

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

cypress:
  secret_key_base: 39dkdj4d9
